### ISSUE TITLE
♻️  Migrate to Reference Style Links

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#101]
Migrate links to the bottom of the page with reference style links. With the way that mkdocs functions. The plethora of links on each page requires a lot of updating. Switching to reference style links allows frequent linking but reduced effort on finding and fixing links with reorganization. This will essentially allow more flexibility. 

https://www.markdownguide.org/basic-syntax/#reference-style-links

- [ ] Add reference links to the bottom of all pages (including images)
- [ ] Hook up all existing links
- [ ] Use easy to understand naming

**Comment by sabaimran** [comment]
Hi @keithrfung ! I was thinking of picking up this issue. I had a couple of clarifying questions.

When you say "Use easy to understand naming", do you mean giving the links useful labels, rather than "1","2","3" as in footnote style?
Also, could you clarify what you mean by "hook up all existing links"? I take that to mean migrating any current inline links to the reference style. 
Should this change apply to all `.md` files across the repo?

**Comment by sabaimran** [comment]
I feel that giving all the links English-language labels can be time-consuming and possibly opinionated, while numbering (e.g., 1,2,3 in order of appearance) is straightforward and systematic, but curious to hear your thoughts.

**Comment by sabaimran** [comment]
I created a PR for updating just the README. I can expand it to include all the other `.md` files in the repo if the format is satisfactory, or I can raise another CR for that :grinning:.

**Comment by keithrfung** [comment]
@sabaimran I commented on the PR instead of here, but I was leaning towards words instead of numbers because there are other features such as footnotes that encourage the use of numbers like so `^1` which could create confusion.

**Comment by sabaimran** [comment]
@keithrfung fair enough, that makes sense! I'll go ahead and implement the change with words, then publish the PR :)
